syntax = "proto3";

package trade;

message PriceRequest {
  string resource_name = 1;
}

message PriceResponse {
  string resource_name = 1;
  double unit_price = 2;
  string currency = 3;
}

message GrantRequest {
  string citizen_id = 1;
  string resource_name = 2;
  int32 quantity = 3;
  int32 reason = 4;
}

message GrantResponse {
  string grant_id = 1;
  string citizen_id = 2;
  string resource_name = 3;
  int32 quantity = 4;
  bool approved = 5;
  int32 reason_code = 6;
}

message MarketTypesRequest {}

message MarketType {
  string name = 1;
  string type = 2;
}

message MarketTypesResponse {
  repeated MarketType markets = 1;
}

service TradeService {
  rpc GetResourcePrice (PriceRequest) returns (PriceResponse);
  rpc GrantFreeResource (GrantRequest) returns (GrantResponse);
  rpc GetMarketTypes (MarketTypesRequest) returns (MarketTypesResponse);
}
